name: Mirror all branches/tags to GitLab

on:
  push:        # Trigger on any push
  delete:      # Trigger on deletions (branches/tags)
  create:      # Trigger on new branches/tags

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all history and refs
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to get all branches and tags

      - name: Push to GitLab mirror
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@git.mpi-cbg.de/rost/sequencing-docker-stacks.git
          git push --mirror gitlab